[changelog]
commit_parsers = [
  { message = "^feat", group = "added" },
  { message = "^refactor", group = "changed" },
  { message = "^changed", group = "changed" },
  { message = "^deprecated", group = "deprecated" },
  { message = "^fix", group = "fixed" },
  { message = "^security", group = "security" },
  { message = "^.*", group = "other" },
]

[workspace]
changelog_path = "CHANGELOG.md"
dependencies_update = true
git_release_enable = false
git_tag_enable = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
publish = true
release_always = false
semver_check = true

[[package]]
name = "hayate"
changelog_update = true
publish = true

[[package]]
name = "hayate-cli"
publish = false
release = false
