PackageIdentifier: ShiinaSaku.Hayate
PackageVersion: 5.0.0
InstallerLocale: en-US
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: hayate.exe
    PortableCommandAlias: hayate
InstallModes:
  - interactive
  - silent
UpgradeBehavior: install
Commands:
  - hayate
ReleaseDate: 2026-06-27
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ShiinaSaku/Hayate/releases/download/v5.0.0/hayate-cli-x86_64-pc-windows-msvc.zip
    InstallerSha256: <INSERT_SHA256_FROM_RELEASE>
  - Architecture: arm64
    InstallerUrl: https://github.com/ShiinaSaku/Hayate/releases/download/v5.0.0/hayate-cli-aarch64-pc-windows-msvc.zip
    InstallerSha256: <INSERT_SHA256_FROM_RELEASE>
ManifestType: installer
ManifestVersion: 1.9.0
